@startuml
!include <archimate/Archimate>
sprite $bProduct jar:archimate/business-product

archimate #Application "Behov\nog krav" as behov<<application-process>>
archimate #Business "Oversikt over\ninteressenter" as interessent<<business-process>>
archimate #Business "Behov for\nterminologi" as terminologib<<business-process>>
archimate #Application "Utrede" as utrede<<application-process>>
archimate #Business "Sikre gjenbruk\nog nytte" as gjenbruk<<business-process>>
archimate #Business "Forankring" as forankring<<business-process>>
archimate #Business "HUKI for\ninteressenter" as interessenter<<business-process>>
archimate #Application "Utvikle" as utvikle<<application-process>>
'archimate #Business "Implementere\nprogramvare" as programvare<<business-process>>
archimate #Business "Utvikle\nverdisett" as uverdisett<<business-process>>
archimate #Business "Forvaltningsmodell\nverdisett" as forvaltningsmod<<business-process>>
archimate #Application "Utprøve og\n evaluere" as utprøve<<application-process>>
archimate #Business "Kvalitetssikring\nav verdisett" as kvalitetssikre<<business-process>>
archimate #Application "Realisere" as realisere<<application-process>>
'archimate #Business "Publisere" as publisere<<business-process>>
archimate #Business "Publisere\nverdisett" as pverdisett<<business-process>>
rectangle "Normering" as normering <<$bProduct>> #Application

note "Interessenter \nog commitment" as int
note "Interessenter" as int2
note "Behov for\nklinisk koding og\nstandardisert terminologi" as beh
note "Hvilke brukere (klinikere)\nog terminologimiljøer" as beh2
note "Publiseres som\nen del av IG" as pub2
note "Publiseres på plattform\nsom egner seg for forvaltning" as pub
note "Avgrenses av\nanvendelsen" as utv
note "Kan brytes opp i utvikling av\nIG, verdisett og programvare" as utv2

'archimate #Business "Forvaltning" as forvaltning<<business-process>>

behov  <|-up- interessent
behov <|-left- terminologib
utrede <|-up- gjenbruk
utvikle <|-down- uverdisett
forvaltningsmod -up-|> uverdisett
realisere <|-down- pverdisett
utprøve <|-- kvalitetssikre
forankring <|-up- interessenter
forankring -down-|> utvikle

behov -> utrede
'forankring --> utvikle
utrede -down-> utvikle
utvikle -down-> utprøve
utprøve -left-> realisere
realisere -up-> behov
realisere -left-> normering

'realisere -down-> forvaltning

beh -right- terminologib
beh2 -right- interessent
forankring .right. int
kvalitetssikre .down. int2
pverdisett .down. pub
pverdisett -left- pub2 
'pub2 .up[hidden]. terminologib

utv .up. behov
utv .up. utrede
realisere .right. utv
utv .right. utvikle
utv .down. utprøve
'utv .left. realisere

'uverdisett -up- utv
utrede -right[hidden]- forankring
uverdisett -right- utv2

@enduml