title: HL7 Norway Best Practice
description: HL7 Norway Best Practice
logo: assets/images/logo.png
#baseurl: "/best-practice-material/" # the subpath of your site, e.g. /blog
url: "https://thomiz.github.io" # the base hostname & protocol for your site, e.g. http://example.com
remote_theme: just-the-docs/just-the-docs

#exclude: README.md
exclude:
- vendor/bundle/ruby
- Gemfile
- Gemfile.lock
- examples/
#- images/
#- docs/dgi/
- docs/horingsvar/
- docs/FHIR-faglig-forum/agenda/
- docs/FHIR-faglig-forum/referat/
- docs/FHIR-faglig-forum/planlegging/
- docs/FHIR-faglig-forum/presentasjon/
- docs/FHIR-faglig-forum/mal-agenda.md

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.6"

collections_dir: /docs/FHIR-faglig-forum/
collections:
  agenda:
    permalink: /agenda/:name
    output: true
  referat:
    permalink: "/referat/:path/"
    output: true

#just_the_docs:
#  collections:
#    agenda:
#      name: "Agenda FHIR fagforum"
#    referat:
#      name: "Referat FHIR fagforum"

plugins:
  - jekyll-seo-tag
