title: HL7 Norway Best Practice
description: HL7 Norway Best Practice
logo: assets/images/logo.png
#baseurl: "/best-practice-material/" # the subpath of your site, e.g. /blog
url: "https://thomiz.github.io" # the base hostname & protocol for your site, e.g. http://example.com
remote_theme: just-the-docs/just-the-docs
#exclude: README.md
exclude:# from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
  - Gemfile
  - Gemfile.lock
  - README.md
  - examples/
  - docs/dgi/
  - docs/horingsvar/
  - images/

#mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
#  version: "9.1.6"

plugins:
  - jekyll-seo-tag
