site_name: HL7 Norway Best Practice
repo_url: https://github.com/HL7Norway/best-practice
repo_name: HL7-Norway-Best-Practice
site_author: HL7 Norway
nav:
    - Innledning: index.md
    - FHIR fagforum: 
      - FHIR fagforum: FHIR-faglig-forum/index.md
    #- Høringssvar:
    #  - horingsvar/index.md
    - no-domain: 
      - innledning: no-domain-metode/index.md
    #- Den gode implementasjonsguide: 
    #  - dgi/index.md
    - Profilering:
      - Nasjonalt profileringhierarki: no-profileringsierarki.md
      - Prinsipper for nasjonal profilering: no-basis-principles.md
      - Sjekkliste for basisprofiler: no-basis-checklist.md
      - Metode for utvikling av områdeprofiler: no-domain-metode/innledning.md
      - Internasjonale referanser for områdeprofiler: internasjonale-refs.md
      - Sjekkliste for publisering av områdeprofiler: no-national-checklist.md
theme:
  name: material
  logo: images/logo.png
  #custom_dir: material/.overrides
  features:
    # - navigation.path #sponsorfeature
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    # - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/git-alt
  favicon: images/logo.png
markdown_extensions:
  - mdx_truly_sane_lists
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - attr_list
  #icon:
  #  logo: logo
plugins:
  - search
  - git-revision-date-localized:
      type: datetime
 # - with-pdf:
 #     cover_subtitle: "currentbuild"
 #     copyright: ""
 #     # two_columns_level: 3
 #     output_path: ./pdf/best-practice.pdf